/**
 * Punto único de íconos (Tabler). Importar desde aquí, no de @tabler directo,
 * para poder cambiar de set en un solo lugar a futuro.
 * Tabler coincide con los nombres usados en el diseño de Figma.
 */
export {
  IconMail,
  IconLock,
  IconEye,
  IconEyeOff,
  IconBrandXbox,
  IconBrandDiscord,
  IconBrandGoogle,
  IconBrandApple,
  // Tab bar
  IconHome,
  IconSearch,
  IconUsers,
  IconUsersGroup,
  IconMailbox,
  IconDeviceGamepad2,
  IconCalendarEvent,
  IconHeadset,
  IconShield,
  IconChecklist,
  IconLayoutDashboard,
  IconUser,
  IconBell,
  IconSettings,
  IconShieldLock,
  IconLogout,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconArrowsSort,
  IconAdjustmentsHorizontal,
  IconDownload,
  IconCamera,
  IconPhoto,
  IconCalendar,
  IconPhone,
  IconPlus,
  IconCircleCheck,
  IconCheck,
  IconShare,
  IconUpload,
  IconTrash,
  IconBan,
  IconX,
  // Marcas de redes sociales
  IconBrandTiktok,
  IconBrandFacebook,
  IconBrandYoutube,
  IconBrandX,
  IconBrandTwitch,
  IconWorld,
  IconMessage,
} from '@tabler/icons-react-native';

export type { IconProps } from '@tabler/icons-react-native';
